USE gerund_or_infinitive
GO

DELETE FROM [Examples]
GO

INSERT INTO [Examples] ([SourceSentence], [UsedWord], [CorrectAnswer], [AlternativeCorrectAnswer])
VALUES
('In court the accused admitted (to) ... the documents.', 'steal', 'stealing', NULL),
('I always try to avoid ... in the rush hour.', 'drive', 'driving', NULL),
('It isn''t worth ... to the exhibition. It''s really boring.', 'go', 'going', NULL),
('We can''t help ... when my dad tries to speak French. His accent is awful!', 'laugh', 'laughing', NULL),
('We carried on ... until about 2.00 in the morning.', 'chat', 'chatting', NULL),
('Miriam denied ... her husband, but the jury didn''t believe her.', 'kill', 'killing', NULL),
('I used to enjoy ..., but now I don''t.', 'fly', 'flying', NULL),
('Do you fancy ... a film this evening?', 'see', 'seeing', NULL),
('I don''t feel like ... out tonight.', 'go', 'going', NULL),
('Have you finished ... the report yet?', 'write', 'writing', NULL),
('Karen has given up ... meat, but she still eats fish.', 'eat', 'eating', NULL),
('I can''t imagine ... in the country. I think I would get bored after a week.', 'live', 'living', NULL),
('My boyfriend''s job involves ... at least once a month.', 'travel', 'travelling', NULL),
('I keep (on) ... my husband to lose some weight, but he just won''t listen.', 'tell', 'telling', NULL),
('We are really looking forward to ... you again.', 'see', 'seeing', NULL),
('I don''t mind ... housework. I find it quite relaxing.', 'do', 'doing', NULL),
('Does your father miss ... now that he has retired.', 'work', 'working', NULL),
('We will have to postpone ... to the beach until the weather improves.', 'go', 'going', NULL),
('The more you practise ... English the more fluent you will get.', 'speak', 'speaking', NULL),
('I recommended ... a double-decker bus tour as the best way to see London.', 'do', 'doing', NULL),
('I regret not ... more before I got my first job.', 'travel', 'travelling', NULL),
('If I were you, I wouldn''t ... walking through the park at night.', 'risk', 'risking', NULL),
('I spend half an hour ... for my glasses this morning.', 'look', 'looking', NULL),
('Once I open a box of chocolates, I can''t stop ... them.', 'eat', 'eating', NULL),
('A friend of mine suggested ... London in the autumn.', 'visit', 'visiting', NULL),
('They both dislike ... shopping, so they prefer ordering things online.', 'go', 'going', NULL),
('She hates ... late, so she always leaves home early.', 'be', 'being', NULL),
('She said she likes ... for friends because it brings everyone together.', 'cook', 'cooking', NULL),
('My grandmother loves ... classic literature and has a vast collection.', 'read', 'reading', NULL),
('I prefer ... to swimming because I enjoy the feeling of the open air.', 'run', 'running', NULL),
('I can''t afford ... on holiday this summer.', 'go', 'to go', NULL),
('I have agreed ... David back the money he lent me next week.', 'pay', 'to pay', NULL),
('The results appear ... the scientist''s theory.', 'support', 'to support', NULL),
('I have arranged ... Sally outside the restaurant.', 'meet', 'to meet', NULL),
('I won''t be able ... for two weeks after the operation.', 'work', 'to work', NULL),
('We can''t wait ... your new flat - it sounds fantastic.', 'see', 'to see', NULL),
('I chose ... abroad for a year, and it''s the best thing I have ever done.', 'study', 'to study', NULL),
('They have decided ... off the wedding.', 'call', 'to call', NULL),
('Kim deserves ... the job. She''s a very strong candidate.', 'get', 'to get', NULL),
('We''re expecting ... our exam results on Friday.', 'get', 'to get', NULL),
('Tom happen ... at Alan''s when I called in, so I invited him to our party as well.', 'be', 'to be', NULL),
('The organization I work for helps young people ... work abroad.', 'find', 'to find', 'find'),
('Don''t hesitate ... a member of staff if you need anything.', 'ask', 'to ask', NULL),
('I''m hoping ... my own company if I can get a bank loan.', 'set up', 'to set up', NULL),
('I wish I had learnt ... the guitar when I was younger.', 'play', 'to play', NULL),
('When I was at school, we were made ... a uniform. It was awful.', 'wear', 'to wear', NULL),
('Did you manage ... to the airport in time?', 'get', 'to get', NULL),
('Lucy has offered ... me a lift to the station.', 'give', 'to give', NULL),
('We''re planning ... a big party celebrate.', 'have', 'to have', NULL),
('I pretended ... enthusiastic, but really I didn''t like the idea at all.', 'be', 'to be', NULL),
('Sarah always promises ... me in the kitchen, but she never does.', 'help', 'to help', NULL),
('My neighbour refused ... down the music and I had to call the police.', 'turn', 'to turn', NULL),
('Something seems ... wrong with the washing machine.', 'be', 'to be', NULL),
('Jack''s father taught him ... when he was 17.', 'drive', 'to drive', NULL),
('My boss tends ... her temper when she''s feeling stressed.', 'lose', 'to lose', NULL),
('The teacher threatened ... my parents and tell them what I had done.', 'call', 'to call', NULL),
('The police want ... anyone who witnessed the crime.', 'interview', 'to interview', NULL),
('Would you like ... the dress on? The changing rooms are over there.', 'try', 'to try', NULL),
('Please don''t forget ... the door before you leave.', 'lock', 'to lock', NULL),
('If you need ... early, just let me know in advance.', 'leave', 'to leave', NULL),
('I made a list so I would remember ... a present for everyone.', 'buy', 'to buy', NULL),
('He spent hours in the garage, trying ... the car.', 'repair', 'to repair', NULL),
('They would love ... a live concert by their favorite band.', 'see', 'to see', NULL),
('They frequently advise me ... cash when traveling abroad.', 'pay', 'to pay', NULL),
('If the weather worsens, they might allow us ... early for safety reasons.', 'leave', 'to leave', NULL),
('He asked a friend ... him move to his new apartment.', 'help', 'to help', NULL),
('Our friends invited us ... away for the weekend.', 'go', 'to go', NULL),
('They need you ... in a form with your contact details.', 'fill', 'to fill', NULL),
('The officer ordered him ... down while they sorted things out.', 'sit', 'to sit', NULL),
('It took some convincing, but they persuaded me ... to the party in the end.', 'come', 'to come', NULL),
('I had to tell them ... quiet so the baby could sleep.', 'be', 'to be', NULL),
('The manager wants you ... the changes in the report to the clients.', 'explain', 'to explain', NULL),
('Can you ... me (to) carry these suitcases?', 'help', 'help', NULL),
('You had better ... now if you want to catch that train.', 'leave', 'leave', NULL),
('Let me ... for coffee - it must be my turn.', 'pay', 'pay', NULL),
('Sue makes her two teenagers ... the washing-up every evening after dinner.', 'do', 'do', NULL),
('There''s a lot of traffic today, so we may ... a bit late.', 'be', 'be', NULL),
('It might ... tomorrow, so please bring an umbrella or a raincoat.', 'rain', 'rain', NULL),
('I must ... to phone Harry - it''s his birthday today.', 'remember', 'remember', NULL),
('Should we ... a table for tomorrow night? It''s a very popular restaurant.', 'book', 'book', NULL),
('You look tired. Would you rather ... in this evening and watch a film?', 'stay', 'stay', NULL)

GO